apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nbenave/ArgoAPP_conf.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc # Internal service name of k8s server
    namespace: argocd-testing
  imagePullSecrets:
    - name: dockerhub-secret
  syncPolicy: # if namespace not exist creates it
    syncOptions:
      - CreateNamespace=true
    automated:
      # enable override manual commit
      selfHeal: true
      # delete the component when configuration has been removed
      prune: true


