apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment-test
spec:
  selector:
    matchLabels:
      app: argocd-app-test
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-app-test
    spec:
      containers:
        - name: argocd-app-test
          image: benave/dev:argo-app-test-latest
      imagePullSecrets:
        - name: dockerhub-secret
